### ISSUE TITLE
Fix for current UEFI firmwares - trackpad not working

### ISSUE THREAD

**Issue by jonathancaudill** [jc-bao/surface-laptop3-ventura#6] opened 2024-12-03 13:20 UTC
Excellent repo. Was having a lot of trouble getting it to work with my machine at first--everything was smooth, but I couldn't get it to pick up my trackpad. Was able to implement some fixes thanks to an old EFI for Monterey/Sonoma, and now it should work OOB for folks who were having trouble. 
#1 /jlempen/Surface-Laptop-3-OpenCore

as @jlempen suggests, maybe a UEFI firmware downgrade would work for some people. This method is probably preferred, but is also somewhat dangerous and has the potential to go badly. Incidentally, I had already wiped my hard drive, so I couldn't edit the UEFI on the motherboard. Turns out some changes to kexts and sequencing was all that was needed. The trackpad isn't mac-level smooth, but it's better than nothing.

I can fork or compile the changes into a pull request if you like--let me know.

**Comment by jc-bao** [comment] 2024-12-03 13:33
Hi @jonathancaudill, thank you for your effort and for sharing your experience! You’re absolutely right—downgrading the Surface firmware to version 6.2 does help make the trackpad work more smoothly. A PR would definitely be welcomed; it’s great to see contributions from the community.

Regarding the trackpad issue you mentioned, could you clarify if the problem is related to jittering? We’ve also observed that using Surface firmware 6.5 allows the trackpad to function, but it experiences occasional jumps.

**Comment by jonathancaudill** [comment] 2024-12-05 10:05
Of course! Happy to contribute what I can.

Yeah, so the issue for me was that using the EFI in this repo, my laptop just straight up wouldn't boot a usable version of Sequoia. It would boot into Mac Recovery, but the trackpad and keyboard didn't work so I had no way to finish the install (I didn't want to fix these issues post-install in case Sequoia proved too difficult).

I moved several downgraded kexts in and edited the plist to change the order and remove all traces of BigSurfaceSL3 and that fixed it... Not sure why my laptop seems to be the odd one out here haha.

To be clear, I'm still experiencing trackpad lag. It's nothing unbearable, and it was present when I was running Ventura as well, so it's either an issue with the kexts I'm using or an issue with the Surface firmware (which I'm frankly not sure how to safely downgrade without hours of headache and potential damage, especially since I've wiped Windows off my laptop).

That said, the trackpad lag is relatively minor (to me) and hopefully my fixes could help someone else struggling to get the EFI to work with Sequoia on SL3 i7 13.5"? I can make a fork if you want to take a look at the changes I made.

**Comment by jc-bao** [comment] 2024-12-05 14:51
tbh, i think the firmware is quite important here. if you want to use latest firmware from microsoft and you are okay with the laggy trackpad, then feel feel to use a higher version of bigsurface kernel extension. otherwise, i have updated the readme with instruction about how to downgrade the kernel. all you need is to prepare a linux bootable usb, start from it, run the downgrade programm, then everything shall work.

**Comment by jonathancaudill** [comment] 2024-12-05 17:59
Hmmm, yeah. I was trying to do that, but it was proving difficult. Kept getting error codes, presumably because I wiped everything off my machine before installing MacOS? Is it even possible to downgrade the UEFI that's stored on the motherboard? 

I almost tried it but frankly it scared me--if something went wrong I'd actually have a bricked machine, no? Isn't the UEFI on the motherboard essential for starting up the computer, even with OpenCore?

**Comment by jc-bao** [comment] 2024-12-05 18:20
that's right. the firmware downgrade is pretty mature for linux on surface so shall be fine. if you are okay with jittering mouse, then a right version of bigsurface text should be enough. i will close this issue for now since you can boot into the system and the README got updated ;)

**Closed as completed by jc-bao** 2024-12-05 18:20 UTC
